In [92]:
import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
import os.path

In [104]:
s1 = pd.Series([0, 1])
s2 = pd.Series(['a', 'b'])
pd.concat([s1, s2], axis=1)

   0  1
0  0  a
1  1  b

In [116]:
col_dict = {}
directory = "tickers-actual"
for filename in os.listdir(directory):
    curr_df = pd.read_csv(directory + '/' + filename)
    print(curr_df['close'])
    #curr_col = curr_df['close']
    #col_dict[filename] = curr_col
col_dict

0     32.85
1     34.53
2     33.51
3     33.08
4     32.70
5     31.75
6     31.57
7     32.81
8     33.39
9     33.51
10    34.17
11    35.04
12    34.58
13    35.47
14    36.24
15    36.28
16    35.94
17    36.27
18    36.69
19    36.19
20    35.92
21    35.20
22    34.96
23    35.10
24    34.56
25    34.89
26    34.45
27    35.09
28    34.91
29    34.55
      ...
70    27.96
71    28.58
72    29.31
73    28.94
74    28.85
75    29.12
76    30.42
77    29.10
78    26.62
79    26.60
80    26.42
81    26.58
82    26.36
83    26.75
84    26.99
85    26.92
86    26.96
87    26.89
88    26.86
89    26.90
90    26.78
91    26.60
92    26.79
93    26.89
94    27.63
95    27.55
96    27.52
97    27.33
98    27.07
99    26.31
Name: close, Length: 100, dtype: float64
0     121.85
1     122.28
2     120.83
3     118.35
4     118.47
5     116.32
6     113.86
7     119.65
8     119.97
9     116.27
10    120.91
11    125.72
12    124.23
13    123.55
14    124.84
15    126.32
16    125.22
17    124.55
18    124.65
19    124.33
20    122.70
21    123.11
22    121.98
23    120.39
24    120.09
25    119.84
26    118.98
27    119.11
28    119.34
29    118.86
       ...
70    111.92
71    111.36
72    110.98
73    111.07
74    109.98
75    110.04
76    109.71
77    109.80
78    109.55
79    108.41
80    107.53
81    107.55
82    107.02
83    107.80
84    107.54
85    108.30
86    108.66
87    108.11
88    108.44
89    107.31
90    107.01
91    106.73
92    106.24
93    105.31
94    105.59
95    105.44
96    105.24
97    104.58
98    103.89
99    102.94
Name: close, Length: 100, dtype: float64
0     101.00
1     100.95
2      99.91
3      98.92
4      98.28
5      97.84
6      95.97
7      98.40
8      98.71
9      95.89
10     99.69
11    102.24
12    101.16
13    101.45
14     97.62
15     97.07
16     92.83
17     91.49
18     91.73
19     92.86
20     93.01
21     90.11
22     89.40
23     88.79
24     88.80
25     86.97
26     84.96
27     86.00
28     86.75
29     86.93
       ...
70     76.87
71     76.43
72     76.43
73     76.83
74     75.65
75     76.18
76     76.67
77     76.89
78     79.20
79     79.57
80     80.75
81     81.05
82     79.79
83     77.45
84     76.82
85     75.19
86     74.58
87     74.22
88     75.53
89     75.45
90     75.31
91     76.64
92     77.26
93     77.69
94     79.48
95     79.92
96     79.59
97     79.10
98     78.17
99     77.65
Name: close, Length: 100, dtype: float64
0     68.97
1     69.05
2     68.20
3     66.98
4     66.21
5     64.94
6     64.40
7     66.11
8     65.40
9     66.27
10    68.57
11    69.19
12    68.32
13    69.33
14    69.77
15    70.49
16    65.65
17    65.12
18    64.56
19    64.75
20    64.29
21    64.03
22    64.05
23    63.42
24    63.88
25    63.40
26    63.57
27    63.63
28    63.55
29    63.51
      ...
70    64.14
71    63.69
72    63.88
73    63.60
74    63.33
75    62.74
76    62.54
77    62.25
78    62.53
79    62.83
80    62.96
81    62.92
82    62.64
83    62.13
84    61.88
85    62.12
86    62.02
87    62.04
88    61.72
89    61.87
90    61.60
91    61.76
92    61.80
93    61.60
94    62.00
95    61.69
96    61.55
97    61.51
98    61.63
99    61.48
Name: close, Length: 100, dtype: float64

KeyError: 'close'

In [ ]:
# make a data frame with 20 of the csvs' CLOSE columns
df_list = []
directory = "tickers-actual"
for filename in os.listdir(directory):
    df_list.append(pd.DataFrame.from_csv(os.join))

In [93]:
data = pd.read_csv('daily_ACN.csv')
data

     timestamp     open      high       low   close   volume
0   2018-02-16  160.960  163.6000  160.8450  162.66  1997852
1   2018-02-15  160.390  161.1100  158.1100  161.06  1815828
2   2018-02-14  156.010  160.1200  155.1500  159.79  2488848
3   2018-02-13  154.200  156.9900  153.9900  156.84  2029692
4   2018-02-12  154.670  156.4700  153.9000  154.95  2229969
5   2018-02-09  151.690  154.9900  148.7900  153.84  3643267
6   2018-02-08  155.310  155.4700  150.3700  150.51  2561721
7   2018-02-07  154.220  158.9300  153.0700  155.15  2899684
8   2018-02-06  150.290  155.1800  149.4300  154.69  3892071
9   2018-02-05  156.120  159.2700  150.7300  151.83  3279792
10  2018-02-02  159.980  160.2700  156.6300  156.90  1996693
11  2018-02-01  160.155  161.1300  159.5400  160.46  1688252
12  2018-01-31  160.090  160.9450  159.7300  160.70  1834626
13  2018-01-30  160.960  161.1600  159.1100  159.70  1658261
14  2018-01-29  162.330  162.6000  160.9700  161.19  1258390
15  2018-01-26  161.250  162.5800  160.3300  162.55  1891690
16  2018-01-25  161.120  161.7500  160.6150  160.79  1297824
17  2018-01-24  161.200  161.9900  160.5400  160.60  1927625
18  2018-01-23  161.290  162.0500  160.6400  160.88  1611711
19  2018-01-22  161.210  161.8800  160.8200  161.43  1698171
20  2018-01-19  161.600  162.4980  160.2000  161.75  2217918
21  2018-01-18  160.130  161.0823  159.8200  160.94  1591559
22  2018-01-17  159.100  160.4700  158.8100  160.21  2084323
23  2018-01-16  160.250  160.3700  157.9100  157.96  2778473
24  2018-01-12  159.500  160.6350  158.5700  160.11  2048771
25  2018-01-11  158.900  159.4000  158.0510  159.11  1809182
26  2018-01-10  158.950  159.1500  157.7308  158.90  1618687
27  2018-01-09  158.500  159.4900  157.4535  159.46  3204721
28  2018-01-08  157.370  159.0100  156.8400  158.93  2610112
29  2018-01-05  156.610  157.7200  156.1300  157.67  1587649
..         ...      ...       ...       ...     ...      ...
70  2017-11-06  143.120  144.2100  142.2900  143.93  1488735
71  2017-11-03  143.430  144.6900  143.1001  144.04  1336018
72  2017-11-02  142.500  143.7800  141.9300  143.43  1580288
73  2017-11-01  142.260  143.1900  141.4700  142.96  2052529
74  2017-10-31  143.180  143.2900  142.1550  142.36  2209896
75  2017-10-30  143.390  143.7800  142.1300  143.29  2145041
76  2017-10-27  142.640  143.6100  141.9900  143.28  2367616
77  2017-10-26  141.580  142.9100  141.3400  141.97  1965479
78  2017-10-25  139.000  141.2400  138.6600  141.22  2046217
79  2017-10-24  139.340  139.4300  138.0500  138.91  1202971
80  2017-10-23  139.750  140.1705  139.0500  139.33  1507889
81  2017-10-20  139.170  139.5000  138.5100  139.49  1364863
82  2017-10-19  137.450  138.6700  136.8400  138.62  1278034
83  2017-10-18  138.230  138.6300  137.3600  137.42  1584802
84  2017-10-17  138.910  139.2800  138.2800  138.65  1435183
85  2017-10-16  139.430  139.5700  138.1200  139.09  1453106
86  2017-10-13  139.580  140.0000  138.2000  139.20  1677933
87  2017-10-12  136.980  139.6500  136.1400  139.20  2728422
88  2017-10-11  137.190  137.5200  136.4100  136.91  2472365
89  2017-10-10  137.000  138.0000  136.8450  137.52  1786645
90  2017-10-09  136.250  137.0000  136.0300  136.99  1007984
91  2017-10-06  136.160  136.9700  135.7201  136.25  1275707
92  2017-10-05  135.500  136.3700  135.2700  136.22  1666067
93  2017-10-04  134.520  135.6800  134.4594  135.16  2177311
94  2017-10-03  134.840  135.9700  133.6600  134.25  2534894
95  2017-10-02  135.230  135.8400  134.6200  135.44  2661790
96  2017-09-29  136.910  137.5700  134.8400  135.07  3299483
97  2017-09-28  132.790  137.6800  132.2700  136.32  4238520
98  2017-09-27  137.320  137.5400  136.1200  136.64  3855258
99  2017-09-26  138.500  138.7000  136.7500  136.84  2902690

[100 rows x 6 columns]

In [94]:
train_x = np.matrix(np.arange(99)).reshape(99, 1)
train_y = np.matrix(data['close'][:99]).reshape(99, 1)

In [95]:
valid_x = np.matrix(100)
valid_y = np.matrix(data['close'][99])

In [96]:
lr = LinearRegression()

In [97]:
lr.fit(train_x, train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [98]:
train_y.shape

(99, 1)

In [99]:
lr.predict(np.matrix(100))

array([[ 135.16392942]])

In [100]:
135.16392942 - data['close'][99]

-1.6760705800000153